GPT_MODEL = "gpt-4o"
MAX_TOKENS = 8000
TEMPERATURE = 0.7

TXT_FORMAT = "TXT"
PDF_FORMAT = "PDF"
JSON_FORMAT = "JSON"

UNDERSCORE = "_"
FILE_NAME_PREFIX = "TuringMaschine"
FILE_NAME_QUESTIONS = "Aufgaben"
FILE_NAME_ANSWERS = "Antworten"
FILE_NAME_QUESTIONS_AND_ANSWERS = FILE_NAME_QUESTIONS + UNDERSCORE + FILE_NAME_ANSWERS


SECTION_QUESTIONS = "questions"
SECTION_QUESTION = "question"
SECTION_ANSWERS = "answers"
SECTION_ANSWER = "answer"
SECTION_EXAMPLES = "examples"
SECTION_EXAMPLE = "example"
SECTION_ID = "id"